apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-chat-api-ingress
  annotations:
    nginx: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llm-chat-api-service
                port:
                  number: 80